export const MEMBERS_LIST_REQUEST = "MEMBERS_LIST_REQUEST"
export const MEMBERS_LIST_SUCCESS = "MEMBERS_LIST_SUCCESS"
export const MEMBERS_LIST_FAIL = "MEMBERS_LIST_FAIL"

export const MEMBERS_CREATE_REQUEST = "MEMBERS_CREATE_REQUEST"
export const MEMBERS_CREATE_SUCCESS = "MEMBERS_CREATE_SUCCESS"
export const MEMBERS_CREATE_FAIL = "MEMBERS_CREATE_FAIL"
export const MEMBERS_CREATE_RESET = "MEMBERS_CREATE_RESET"