export const PHOTOS_LIST_REQUEST = "PHOTOS_LIST_REQUEST"
export const PHOTOS_LIST_SUCCESS = "PHOTOS_LIST_SUCCESS"
export const PHOTOS_LIST_FAIL = "PHOTOS_LIST_FAIL"

export const PHOTOS_DELETE_REQUEST = "PHOTOS_DELETE_REQUEST"
export const PHOTOS_DELETE_SUCCESS = "PHOTOS_DELETE_SUCCESS"
export const PHOTOS_DELETE_FAIL = "PHOTOS_DELETE_FAIL"

export const PHOTOS_CREATE_REQUEST = "PHOTOS_CREATE_REQUEST"
export const PHOTOS_CREATE_SUCCESS = "PHOTOS_CREATE_SUCCESS"
export const PHOTOS_CREATE_FAIL = "PHOTOS_CREATE_FAIL"
export const PHOTOS_CREATE_RESET = "PHOTOS_CREATE_RESET"