import { type } from "@testing-library/user-event/dist/type";

export const inputs = [
    {
        id: 1,
        name: "name",
        type: "text",
        placeholder: "Upišite ime",
        errorMessage: "Ima mora imati izmeđju 3-16 znakova i ne smije uključivati znakove ili brojeve!",
        label: "Ime",
        pattern: "^[A-Za-z]{3,16}$",
        required: true,
    },
    {
        id: 2,
        name: "lastName",
        type: "text",
        placeholder: "Upišite prezime",
        errorMessage: "Ima mora imati izmeđju 3-16 znakova i ne smije uključivati znakove ili brojeve!",
        label: "Prezime",
        pattern: "^[A-Za-z]{3,16}$",
        required: true,
    },
    {
        id: 3,
        name: "date",
        type: "date",
        placeholder: "",
        errorMessage: "",
        label: "Datum rođenja",
    },
    {
        id: 4,
        name: "",
        type: "address",
        placeholder: "Upišite adresu na koju želite dostavu",
        errorMessage: "Morate unijeti adresu",
        label: "Adresa",
        required: true,
    },
    {
        id: 5,
        name: "cardNumber",
        type: "text",
        placeholder: "xxxx - xxxx -xxxx -xxxx",
        errorMessage: "Broj kartice mora sadržavati samo brojeve!",
        label: "Broj kartice",
        pattern: "^(0|[1-9][0-9]*)$",
        required: true,
    },
    {
        id: 6,
        name: "ccvNumber",
        type: "text",
        placeholder: "xxx",
        errorMessage: "CCV broj mora sadržavati samo brojeve!",
        label: "CCV",
        pattern: "^(0|[1-9][0-9]*)$",
        required: true,
    },
    {
        id: 7,
        name: "dateNumber",
        type: "text",
        placeholder: "xx/yy",
        errorMessage: "Datum kartice neispravan!",
        label: "Datum isteka",
        pattern: "^(0|[1-9][0-9]*)$",
        required: true,
    },
]